---
collections:
  - name: community.general
    version: 4.6.0
  - name: community.sops
    version: 1.2.0
  - name: ansible.posix
    version: 1.5.4
roles:
  - src: xanmanning.k3s
    version: v2.11.1
