---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
