---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.releases.teleport.dev
      chart: teleport-cluster
      version: 7.3.2
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  values:
    clusterName: "teleport.${SECRET_DOMAIN}"
