# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: networking
type: Opaque
# CLOUDFLARE_API_TOKEN: Profile > api tokens > Zone.Zone Read, Zone.DNS Edit - all zones
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:g3EjQrhjSX/JWl0fuBEAGE3NAfoVtnnFP6nyn3M60PsobvYCAE4vfg==,iv:WoEOexOR28mDr3dKnFSsEjRiCRHMr3yzMK4xQLoFXw8=,tag:RJfG/dilUm2zqK+XEdqdAA==,type:str]
  CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:rJvWNZfdX8qwb4n9HJ7YRdahIwwq7JaqqvUcyup4rtI=,iv:WygQOcnWS1RKrLcPqnnzizMJFgWtU9X4d7qoENcPGVQ=,tag:YRAbMl5AU2sbl/sJjUdAnw==,type:str]
  CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+8JEK/bToCPsQ8GSPrjEqHU=,iv:AkQrwX2XvjoVxzL/5mDfRzo+k5oGEnNiGVGu1FGHVZA=,tag:HxN1PvOpMUnKo7H8RQa1Iw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-09-21T19:13:19Z"
  mac: ENC[AES256_GCM,data:N+ca+faoSQQRLad+A7VlZUxN7agen/eH9wwq5E57fpe9ut6ko1pJ2smO0gpHNNTxUBSG9LTx+7R0b0kMgmaQNnypx93mAn3NHDb/VSz8HhW5gCxdlhehUz9UIE0QyCvFR9W/2GpeG1q2mgOSWOlxv9rGBZVaS13aXleTK9mgxlM=,iv:tB+aSc25pB3uwmeEvJrw+83NM9V1XYsYu1pjhAh9J70=,tag:XPrRdhx41vCk9BMPP1gzuA==,type:str]
  pgp:
    - created_at: "2021-09-21T19:13:18Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA1GgX0oycVV1AQ/9EHLWFnKECHk4CX7xHdmnKtd1pqltNFDs8a1oR23iknAb
        CMNNXjWE9DSPjsWcaajxh78rwTNJSsXZv3uM9Uhj3U+bE0gDMAr2k2zX/0CEG8T/
        +5mRL1/7GVxQkGGtdYr08hjJNz6Ul94IsYw/9pTBG8qgQynjEC5JCsTKp71Xu8pF
        II4+Ho7RaXNjM8DO2LnaJ31jI4FPnhMsrG1MiunNIrHb1MDiZibJbLPyT6uTxTXD
        ANIx/ECMZWKRclLkkk0ovztcQyvl6RMt/rxpJGalLy4QqfLOCD3vQcBF2mg9oAf0
        pZ6+syomGJZNRvRQ3BiLseGZpmOG2IIxrKHeKHcQWQ1so3yUVn+nMfOw2t88GYb2
        bbx7ZM8ym/E/oKFdyu2WYQl3be1PWtuT3obgPmNyHsD9KlINc/T5R+30JwiVM3so
        /GJ1RJsV564hVhr6TIzfYbygP1qwL4B5KX/VE8NX6vU1SsvfW0DjJ+WED9RQOhrq
        X8a0JdvTaUg0E2sUe1a8+d1tfJd6zUv3PAvZ0woDfzZ4/5LAyF/mKGAWoi66JqMq
        HWBjDrS+98VFu2rFJK/fQZZdaa9Y9p1OG4k6pYTQQYRJC0/IBROY/FZQ/dKDoFR5
        JNcn0wKASnCiU4qPlmnQq06kESCEmTJd1Hdrj6E/PNdEyhEXSsnpw1ZwhZ7xPrvS
        XgEmPSBF4VpX7gdXMnzhAFnVcHAliDTfdRRxw8SK/hM2uvqsWdA8LrgCXepirAJw
        A1GEV0MGo08H21PrKRpEdjVzoIz9Pu6gweJQHx9bd7+iwFZqyiW13NE/1YOV6rY=
        =sa0V
        -----END PGP MESSAGE-----
      fp: 17299B027FB6B1C68971411B5FF3C7583ADD1EFB
    - created_at: "2021-09-21T19:13:18Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA5XaZDWXjonIARAAqd8e3XNsEkkVYipW/x4kjuweICGVkJkylSMQ45LtL/lu
        VOcacsVRy/gsJNzF3RBCERN/tEFIeXgrBpTnB2QDtjMJaPGgYNN773qhXDrHo/hn
        1YjG/dWh48ztbTM6xBV2zxw9XJLEatNKN2jSlCwxi5JGrIEEE2JvrXrhtPzcrPxj
        iQfvTXHk6Lb5laBQostoExZiazXWYHS6tHQqGFJ9cOoioA7ceob58jNyCkoVeIig
        sS7JcfKUd+5zvEc1I2uUQWPVOFLSFBCiAv6ryt1MIMvcAnQ9fpXzj+njLXEv5Xpb
        HrBHzMDDVjYuXPw8sb38yM054cdp3pib0INthi4DuI7PF0f9eLOwbBE8Hswukery
        LfQ/RZJGJmGMW/IfzBbk9Jdve+fNQRdiUQUZgPZLrh6okyUSUI+KGXxl68Gl4xxb
        6imBLpHPrPKTORkoOMLpMjHD2bjQOX3YKKW1uJU9WTFRKJ9ywyBerUUkK+8GTBWW
        IbidtCHsbetajMKXA1tPclQ4Rz8VeO6bdXaSwKGO6oXTxLsNbaWSwUDXFwJIvRfx
        HrhGBh6/Lv9dHNYZCF5gx6lmMJje0mGcRRiPRrd5s6OGzTZY5+hHt0rVFDLb6nS4
        iOzLsSbcvluZDck+dpfibV8ZxtRljvrijQ4BTmAKyVaZq2FvZohcFH70PPHCpG/S
        XgH9uFuyOE0Jav9h4E/40jQb4/RyRhIxhL8hGmFKcIdjPBO5lcJkWO1NAXCoyRAY
        eRCX+d8qGqzk9m0fhTr5STa3Oi1QFJHRTDvP51gXRud6IVVnl22iBpj5nNCTl00=
        =h690
        -----END PGP MESSAGE-----
      fp: 147C67A0D68CF30B3C7ED3AB43A189D025B879AC
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
