---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
