# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:wfEmWU2+eBHeywk20k8xoO8SJA==,iv:mrhq7EhhXf+eTHz5Rw1nxwM3QSyJ8UdL2NIHLv3In0U=,tag:9CU5+QpRikXnzXE/wwXvaw==,type:str]
    api-key: ENC[AES256_GCM,data:NtQQ3tZTsqW3V72EUiQzTEeKb54bpvbTUCJ+LWcd38MCaxzB8oUqpg==,iv:9invW1rW9cd5RtVrChOWWmgsEzx1n/CwuWg3bzjPnVs=,tag:MPjmv0ezCeeyNQTN3Bc+zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-20T22:41:27Z"
    mac: ENC[AES256_GCM,data:+onJiLS6fRIYQV9LLjUWOa9AZ6VlawjF3D97t+RTt79Yj8VAGndrYCcUt1q/jk4V55SiKfiJk3zEPlgB7xLHmpsaySucaHhurF2PuPEbWKEEw9NiADec5DpGVB39w1Oo2DHGein//J4fzHWv8O4kTq3/ZGyMX4bWptXUzRjHcbo=,iv:/MKFXKD+O0n9cmhBAbATiDDkn6VuXyTwolgCVTE4DUw=,tag:emxf0wQaLBZYfVbVK9ZnGw==,type:str]
    pgp:
        - created_at: "2021-09-20T22:41:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1GgX0oycVV1AQ//afuV9vvvpSJquSv/UlRfd+lL908D/XXGQh737zI7IBvm
            3q10F5QCHGvf1q+w5klEACtuTCjdxr6f7eZ5QiSZftk1W+vSjEIlLEl8zW4TRyTW
            5HHKvvAnSSu7BJfavhpdjKCEgvxCw6kZT8Q3ajdYKee3eZrt0Uy5DXlteaE4aKvT
            EFsYx1IdvQjbgCOPUz32cPCBd4DxhXrx/yYgcs2hypsVodzdX51uIejlfLIAuEGV
            XRmlwDCzhXZkb8IHUGUiHVPP4zPpTmj6zjabz+RG3Am4d+8f2AiA179QZDJmIlBT
            rh/UozgocHvuqZRTEzGtZbkoqjxwnTNj6mr05YJZ4fRvF33Lr9CsllRhvu4PA019
            vF159H9YF2a86xCv+Lzu0nMOsOEr3DwTR/aY3twsX97+w35Q7zd5XQP4RY26uRSa
            yTRzGPkFLEK2/ZXZrxS+f9Y7uJIHhA2ptv4MdkHpwag41fNLJtZmfbkGp+n9EvT4
            fD7P1SbnK1M1Zbd3hOWJeVT6XCfc3wBC0Sa+gqLJPtL7akwikQ5tS4OH7+jj6C12
            +yc87MGOjkoXOFTT2KJ15T4u38XDV636JrVRTF6NkKRxo0NaO7B5239257bJPojX
            fc+qm6l3LtF9hlrgdFyUSD5PyKjdLLLjgUG4kySS9oj9AR4HsDrQWwrcxfGaIHPS
            XAExMy7UxdNVAbR82N4/WQPp4cJYYw4J6a9Gd/eSuLgjM725SUxsI6QzgNX+48Iu
            GC1yJ1MBscK6jCMQoH4JzXtck0WaxdCxWMzYiqRUqJyfxcaImP8mnW/xN4g+
            =2HWH
            -----END PGP MESSAGE-----
          fp: 17299B027FB6B1C68971411B5FF3C7583ADD1EFB
        - created_at: "2021-09-20T22:41:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XaZDWXjonIAQ//fDeETJj4O4jUzZPUwxpA+dpl1EsuLMu/ceAg5DlZAry6
            smfmYOPGhzd5Fnu626X1BnD+S0NbqncR1JuKM7ikqjG6/UEaXVeDY5aHqEACej/5
            CU8w9o8NNKFtsnfaIp7WsqdMvK7yh9iNEK8eoyZyp3yZuECOXoqWFS39LMoT9lH/
            e1+v9ZLGdroAWTKwTLtEYf1zNvjZrvWbOHfRRZqyBzOZTWu5bK3+R6lWyGZj6vKx
            I3w4slTOojD4kPyibxiiRmoCNycKVT7TKDLGfZbNeXVt6K5pXXRmFnaKtD3Kv9gH
            AxmjGBKUPvoIL1lJfz7oe7WW5bAR+/z6P0aDMrSVerMmYq3F9tpmOSndZ2vezA37
            jwKpp7eeQc1YU3cjQtUK6CESioSafkBb7bhoPoO5vqCaFiy26br+7kdOL03Y7JaY
            DKUtVncGRkrxgxz2Q9j1QacDEyXLkpFpOpFAxqzUskHqXZ+PNRj7GXN827LXH5kp
            MSY66etlc3uWVX1Jgj5ghtzIMGDH+uPJvSVkzRDZaF3EjjdJUK00Y8+xc0c5qDiy
            4VeyH+NOVnW++fqGzjCuZ5BjSHLGJVxnhal9veXU6rlNryPW1wZvg3hgtZ/dRAtz
            gOftRoU0MWioJ2GNiQnAC93UfT3isI5xeqxj6VGqFpJbs689MRskVZV/7V5D7zbS
            XAFbCYCl14pfWDBwERtlmilnGJdr1oRx9akTZJ/WdUFAiZNvhsmQ1hV2Unzlbi6/
            wNPq9C6zRESliZ3EmHVFA9s9VlwFG5Yop5odFjqZO4gyXWDecjY1fxSjBFTz
            =eyNG
            -----END PGP MESSAGE-----
          fp: 147C67A0D68CF30B3C7ED3AB43A189D025B879AC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
