apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-postgresql
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-postgresql
  template:
    metadata:
      labels:
        app: authentik-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authentik
                  key: postgresUsername
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik
                  key: postgresPassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: authentik-postgres-data

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - "amd64"
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
  namespace: networking
spec:
  ports:
    - port: 5432
  selector:
    app: authentik-postgresql
  clusterIP: None
