# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: networking
stringData:
  postgresUsername: ENC[AES256_GCM,data:KqgH5IGpupE=,iv:JDW+eN4Z2QfByNTsF6cj8VceLahW/eaaKqqzivSjNVk=,tag:0fBRtRKxPNA2xvWInBhfdw==,type:str]
  postgresPassword: ENC[AES256_GCM,data:g4F4qgFd0Zy6PASgqjRYiXx02C0=,iv:IE1eLgKDmG5d9HNw0UdTE9T9lMbO4CTRf9VEGugACx0=,tag:wFSF/2hSQZ4kD5qNtuzk2w==,type:str]
  secretKey: ENC[AES256_GCM,data:w/tesAvU3gBdFpS1FZ2lqF57sZY=,iv:NUUusljvvEO0JzyACafvvVSPnXRi0tjw+St09BTVA+Y=,tag:EktmxOE012D/xit1z17dJA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-12-12T18:32:06Z"
  mac: ENC[AES256_GCM,data:uvmN1+DGFzcvnN87AE3LtHDZU2tRJZ5oOZ7FzuPt7j3l8c0V9LgnmxpIu1wVr70+ebk8Fjr0ShqTWbsLlM3tCvTP2d/nufMr1vss2IbgOsYnSbAvB+MrVrCNBV6GteNg9EvqDG8zj2TLZOSqLYrx/pc3z0Rz2098sWJlArrohVk=,iv:z5GynSmDqK4qGWDqrOYxNa53nyYy+VFx+Pog5313Z4A=,tag:PrZlLBNRwYMnEAHKUzjl4g==,type:str]
  pgp:
    - created_at: "2021-12-12T18:30:17Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA1GgX0oycVV1ARAAx8VJI7e1psNrg0K7AgNLqHSvrOMGnoGe0yyaHMqWV4x/
        4NdYG0dh+Y3imVTUap3szrSvmsWUDvkmSUzeqRID8jax+1pPsnoqy+i6bGlR+Mx4
        N1s5o+4bfdLgdnZVdSnDlGSBAWji66BKbpa6HGL1hg9zwQyR56Ir/y1cbEdku7Yq
        ayhuVDLALExG/5unTxZBawkUu2cY6N6fnCNnISv67kZCBRfr0XrE/GOi1Hn1xcyt
        MZ1C07Fw3opP7z3MQOshikQxBYefZGQjB+sclpVKSfQJ6ZPSjc3SW5OdwJ1NnMxb
        nyNYVozfUXrN5rJXP7zYnHPstlIIB8b3wKXxhe8ULRuSKtBNio/VVRUkNbtnTjso
        EP9pqjEX2MpAM9EGsdjMaMgTCJ3aacaNNctUa6nfMv545o1hSbdf0mdawEOM4iff
        xEU6oA+rTugdgUbJCWqPE0DSRTtHTZyE9xlGjSYnLs42AxBSkYY1TrGzWYbk0gut
        prVZgXTW/3nUg8djPRfkd63p30btxrZj1O//6EmM+FQybKT5424+Bs+lT8wFY7hv
        xMqvAuJ0MZAASEINyG++Tk+RjLcV/iPnS/cMZ3s5/QUntFn984cec7K54w6+9itm
        P8TQ+OcL/XbsfnxJoz+1/Gh0CSjPbLjumwEpdd0BtLSrwmgHamrsxDs9D62n1fPS
        XAGOPqxWgEHniN1n5JQ9GbqNFwv2AQ/ozNgsU/cK5cpQJJOXCiZtI7TkjpYdXYOp
        fyv1tlvk6+065tA9cw83/77HESH29v85YYdCC0ElSP4+gBibKeS0O2tC2GAf
        =WLJX
        -----END PGP MESSAGE-----
      fp: 17299B027FB6B1C68971411B5FF3C7583ADD1EFB
    - created_at: "2021-12-12T18:30:17Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA5XaZDWXjonIAQ//cy4SpKSvmkHtm7Ia5+CsvAy2e4fUNMpxgaSrwRmGsywq
        174tNi536oBLjefec73xxqgCv6esgpRR65sR7h9rU0IO8WIqwknWdbbLwq/LxKB0
        4SP4QFmDSQ2itkYnrkeM5bc9/DGDGgzMHoJVgckMcu2Pv6yURVto4MqCfQAcbKJ8
        hiqPxsJKyykwTcHprI3UN3cMKf3qBHiWVQMDiY1bboeHCOGJKW3t/ouIoQzSyq14
        h2DAw4/r07wWcbEW/s0mSvquJFeejOtDDXLVdjMHExDKHNGhwnTfQsieux9JMuQf
        7warIN1CNFOuKnnap7aBLjAu58iBl0Yk5y1sMtE+mLQOpxXbW7ehGK4RmJ8B7Lmm
        N1SIzMYPFgJ7AqVfUQZHZ1Dtk9R1+0xoxw/6o1DlBzCwtcFzJqF3bh4eGmDZaeWX
        FXT+kB6UK+M2e6QYcEG634TO69PSCECJZhBaHHGs+6gRCQcVKU7f6H0E6eRGefwR
        ejuHdPqEasyLOKIHuowjqFUwWVL6p/n07uY/saYbJmaSTOxXixkBQG3OlAX+bhuZ
        nrLknB3J9K9EfLV2mSRF65kZokE+JhfoqQnRVlM9x5ctdG0EWzfcCAbka6q5FKK/
        JdFkcfyZEM0adZwGx+3DOfg+jGQs7XsbzR6dhn3P9h3f0/EMtK/zlXbT0FdWr2PS
        XAGmkYaH0AVLQlRBSdY8FYJ6YYQAAYEX8kt49VGybYOxLNocLgjh94I8k6vz83RS
        Y0CMI/f+bLExc6Yk1tQlqa8NrMqXq8wmtJxIyV1uZ7aaEqHR3/vE7W1Q/Kmp
        =FnJF
        -----END PGP MESSAGE-----
      fp: 147C67A0D68CF30B3C7ED3AB43A189D025B879AC
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
