---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 6.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   repository: ghcr.io/k8s-at-home/monica
    #   tag: v0.1.0
    env:
      TZ: "America/Denver"
      APP_URL: "monica.${SECRET_DOMAIN}"
      APP_KEY:
        valueFrom:
          secretKeyRef:
            name: monica-secret
            key: apiKey
      DB_DATABASE: monica
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: "monica"
        hosts:
          - host: "monica.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls.monica
            hosts:
              - "monica.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
    # persistence:
    #   data:
    #     enabled: true
    #     existingClaim: hajimari-config-v1
    # podAnnotations:
    #   configmap.reloader.stakater.com/reload: "hajimari-settings"
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128M
