# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:HoiLNXx4/XbgAS20yhz5NSObqbZJ8ZM8RP+S4ZscBu7U0dX7eUgA/8ep7cPAr2nLqZfgQoLCq+08FiDBVyfA592vjLq3CQSDOrp3UDN1H5G24QwiCtiB3mQ6Brn20teIF00TR9wIPTVl0jYagJB753Bot7Ll0aM/,iv:wE/GNXjv0LbPbGP/stX+o71XqDjk/pn54aWQXlZalyk=,tag:OF1idID17rX1y0YWAumPEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-12T22:47:17Z"
    mac: ENC[AES256_GCM,data:DcLlAoK78BfkFwf14N5tuSJViQBCrVp9ocat12iujBLeHjoPUykuI0heAFOTWNrsCT5aPHgqR30jGTrzYFC5ja229NqVvjp2aCbtXdNpXhQaYPWo0Ajk2E1F+zlupwbvy/spCov04Byzr4ppLjqkOltzqFheqlMVPcd2t/ZwJDo=,iv:g1DQCySC3Gghohm5sW6pb8faYmuPWulwUZhrwGUsdi0=,tag:vcKKA43F+1WYKeL9/wau7g==,type:str]
    pgp:
        - created_at: "2021-08-12T22:47:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1GgX0oycVV1ARAAjmD0U/zH58BDcY/qB3fGPr+A/Cot8nns1V8sJ6YDqXAv
            Wt6BtzU17EDFt8/9iIwYi5Oc/t/92eTcVO6Tr3bhJSK/O4IrmkDqQRELDDVVhaft
            324k6m98SFdsGvamzCMZgItQeMZSqfvRNXoOqTJ8jgi5VPqkaa0pbyMKvhXnf5zr
            Ladxue57tBHnx6w2+HhP7YJDviDJd0AdkyDgKBUZWnPo1IxILZVGZQ1UqjlrpKzQ
            qAreW+ckwsp4CQJcoLPJO0Ra3uwZ6SaLkNA7kUXlLbhAfHKL9E751JbNeG2svQk+
            7c1yu2EKC7D/tFmE1pyvbEmpuZkXXwFue05BssVoBl3vrTRuWDWWuE4xXLDT6SkO
            7e2xqnXdbQQd3N42k3SE00WE+t3N1tsQI15gzMDeLpmB+rBvT9Sdol+BokpK8fmT
            zL5K0Mw2xfrU/U2TGbzlHf7BaVNjwGA2G0cabNEtmhtUZPxv2Ub01SmYyR9FyuDM
            agt/VdjV4BQoTiWuPCeMjUKlIhaKo35GLggIukHIexA9nMBMVqbh0whP0KK141sp
            pyBn/LIwteXHVsKHUgQJnW3/T3inUASLbeVYQX17gWe+N8PtDRo67CksLKOSaisa
            BrL1b5mqLcez0hr2Kq9E+hdH/nK2nqdHSBKUmkj7sakSxllLkUcG4Oc5vmDo4rbS
            XAEcKnqtm3sypqJo04t38H3vQs702lbdsxrrtlXiOl3C0J2KU/jDo91xwERmT/pv
            +V8DZzyTRuh7oGq00KdAku6lBV1u3Pvh73zqPyVXHtss11ZILrOpcRfXdxv8
            =xsKy
            -----END PGP MESSAGE-----
          fp: 17299B027FB6B1C68971411B5FF3C7583ADD1EFB
        - created_at: "2021-08-12T22:47:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XaZDWXjonIAQ//QLt8nmQapWpBzBlJseiR0Dm3KzPCUFt4+J1ty8ZN9m2R
            uaX/R4nAe5jiG7llF00h16JOa6nbeCwxOFjbsZ1edT/fC+MxeF8Gxi4PfuZwC/JQ
            2w+aNZ3+uyHckNDYBsa4qMAWIrretKbnpLnohDVQ/fjF/QoQXKEH2LA7oobZZFwE
            SCywjHAzrl7D/a1Kl4HCnfJkMdxnB6fdkyoQYWS3qqy42o3OG1UVYdHiPqoib/Zi
            ffrYByYyYCjgRprdn1/OAxUsjoPccXGg7r7JH7vTQ03dnBOY5UuKt+nPz1LiVp/N
            S+u+gWTR8eMtJR4vmibY0K9++VMPXQ+t/PPslf5AWQkr3FttupRuuPa15ELSODkA
            E2Pv9rYw0meLB0hoGE10dzQkaAttFSoYS8DdREyFb0o+c6fJpwY/gENd4gfGCUBn
            pSuQmRRBYPgr6eqGV29q+tSbXy10AOwkjZ5n1EmJSYKjfpida6Sb29MRDYEdxQep
            tZTX92eCyE1D5d7EKivFjVxVjJhBm1NSFKdSxyx1Rs/4GhnofK+Qb2QJtCcSdoZc
            ZuqXzPUMSeDTBTXRFaqbvgHNEB/wz5GyQkfwIHL2uCYPllRGW9LwlFMLs3G9dLeU
            GO6pqO1cva+itE1daass5WpGrfv9s8X6Oo2DWtojhMMLLmYQ/SRh02nmqy3E+1nS
            XAHC1T2HyfqWqYbFMu/Gxrh5ZYqAK8IJuCyIhx2v6z1oYSvOekIB/cpysNKdDq6+
            S7vyODcJ5FnW6CvpWiHPOWGe09IrGd78MOAXldKPZ66H8qBaEfTvXEQzQWNT
            =ntZh
            -----END PGP MESSAGE-----
          fp: 147C67A0D68CF30B3C7ED3AB43A189D025B879AC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
