---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 5m
  values:
    imageTag: java8
    # resources:
    #   requests:
    #     memory: 6Gi
    #     cpu: 2000m

    minecraftServer:
      eula: "TRUE"
      version: "1.16.5"
      type: "CURSEFORGE"
      # cfServerMod: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-slice-of-pi2-atm-slop2/download/3452307/file"
      cfServerMod: Enigmatica6Server-0.5.11.zip
      ops: kpfromer
      maxPlayers: 10
      pvp: true
      # memory: 6144M
      serviceType: LoadBalancer
      loadBalancerIP: "192.168.0.75"
      servicePort: 25565

    # persistence:
    #   dataDir:
    #     enabled: true
    #     existingClaim: nfs-minecraft-pvc
