---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-atm6
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
