---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.24.0.4930-ab6e1a058
    env:
      TZ: "America/Denver"

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.50.105
            path: /mnt/kpfromer-22TB-Z2/services/plex/config
        mountPath: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.50.105
            path: /mnt/kpfromer-22TB-Z2/services/plex/media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory

    # TODO:
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: feature.node.kubernetes.io/custom-intel-gpu
    #               operator: In
    #               values:
    #                 - "true"
    #         - matchExpressions:
    #             - key: kubernetes.io/hostname
    #               operator: In
    #               values:
    #                 - k8s-4
    #                 - k8s-5
    # resources:
    #   requests:
    #     gpu.intel.com/i915: 1
    #     cpu: 1000m
    #     memory: 1000Mi
    #   limits:
    #     gpu.intel.com/i915: 1
    #     memory: 16000Mi
