---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "plex.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 80
        # tls:
        #   - hosts:
        #       - "plex.${SECRET_DOMAIN}"
  tls:
    - hosts:
        - "plex.${SECRET_DOMAIN}"
