apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  ports:
    - port: 32400
      targetPort: http
      protocol: TCP
      name: http
  type: LoadBalancer
