---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.14.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    postgresqlUsername:
      valueFrom:
        secretKeyRef:
          name: journal-site-secret
          key: username
    postgresqlPassword:
      valueFrom:
        secretKeyRef:
          name: journal-site-secret
          key: password
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128M
