---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.13.11
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    # TODO: improve to use secret
    postgresqlUsername: "kpfromer"
    postgresqlPassword: "kpfromer123"
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128M
