---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 32Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
