---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  chart:
    spec:
      sourceRef:
        name: k8s-at-home-charts
        namespace: flux-system
        kind: HelmRepository
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 7.1.2
  interval: 5m
  values:
    image:
      repository: photoprism/photoprism
      tag: "20220121"
    env:
      TZ: "America/Denver"
      PHOTOPRISM_ORIGINALS_PATH: /media/Photos/originals
      PHOTOPRISM_ADMIN_PASSWORD: ${SECRET_PASSWORD}
    ingress:
      main:
        enabled: true
        annotations:
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "download-box"
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "kube-system-forwardauth-authelia@kubernetescrd"
          cert-manager.io/cluster-issuer: letsencrypt-production
          # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          # external-dns/is-public: "true"
        hosts:
          - host: "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "photos.${SECRET_DOMAIN}"
            secretName: photoprism-tls
    persistence:
      config:
        enabled: true
        existingClaim: photoprism-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.0.55
            path: /mnt/kpfromer-22TB-Z2/kpfromer/
        mountPath: /media/Photos/originals
    resources:
      requests:
        memory: 1000Mi
        cpu: 1
      limits:
        memory: 2000Mi
