---
# Pulled from https://github.com/paulkiernan/homelab-cluster/blob/62954ebe1c3f2af0063a6145f121a2939d0e7567/cluster/core/rook-ceph/ceph-cluster/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.7.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
  values:
    operatorNamespace: rook-ceph

    toolbox:
      enabled: true
    # TODO: UPDATE TO TRUE

    monitoring:
      enabled: false

    cephClusterSpec:
      mon:
        count: 3
        allowMultiplePerNode: true

    storage:
      # docs: https://rook.io/docs/rook/v1.7/ceph-cluster-crd.html
      useAllNodes: false
      useAllDevices: true
      # nodes:
      #   - name: "titian01"
      #     devices:
      #       - name: "sdb"
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-production
        host:
          name: "rook-ceph.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - secretName: "tls.rook-ceph"
            hosts:
              - "rook-ceph.${SECRET_DOMAIN}"
