---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: default
spec:
  chart:
    spec:
      sourceRef:
        name: k8s-at-home-charts
        namespace: flux-system
        kind: HelmRepository
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: stash
      version: 3.2.0
  interval: 5m
  values:
    image:
      tag: v0.12.0
    env:
      TZ: "America/Denver"
    ingress:
      main:
        enabled: true
        annotations:
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "download-box"
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: "kube-system-forwardauth-authelia@kubernetescrd"
          cert-manager.io/cluster-issuer: letsencrypt-production
          # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          # external-dns/is-public: "true"
        hosts:
          - host: "stash.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "stash.${SECRET_DOMAIN}"
            secretName: stash-tls
    persistence:
      config:
        enabled: true
        existingClaim: stash-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.0.55
            path: /mnt/kpfromer-22TB-Z2/kpfromer-encrypted/Stuff/Videos
        mountPath: /media
        readOnly: true
      images:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.0.55
            path: /mnt/kpfromer-22TB-Z2/kpfromer-encrypted/Stuff/Images
        mountPath: /images
        readOnly: true
    resources:
      requests:
        memory: 1000Mi
        cpu: 1
      limits:
        memory: 2000Mi
