---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.2.9
    env:
      TZ: "America/Denver"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${HOME_ASSISTANT_ADDR}"
        # ports:
        #   sonos:
        #     enabled: true
        #     port: 1400
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls.home-assistant
            hosts:
              - "home.${SECRET_DOMAIN}"
    addons:
      codeserver:
        enabled: true
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              cert-manager.io/cluster-issuer: letsencrypt-production
            hosts:
              - host: "home-config.${SECRET_DOMAIN}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: tls.home-assistant-config
                hosts:
                  - "home-config.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
