# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:y4hRZnnHXIgSMzqRsKlIpNOh5TQu2ra/kcUE0YgzVEOieub3pQ==,iv:LecfguvO9klb6gI3T5Gz4gWOwEFit3CYe26Zy4yfjNo=,tag:BGg75SbrohKYMv5CuU/S2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-12T19:39:04Z"
    mac: ENC[AES256_GCM,data:jWhHoa8J2LhLNgxtH62K4ypAXhO5mBE8Fp0BBIZEmA38NvKMsmU+f7HMqFSaz0M8mBSGhhwo4NOqv9sM9+dvuaGzMT3PLaWENIFK86r6AUOsS1b6rNux03E0ec+7DW/WKANiwFFRkC6I7ORaUHnHL+B2mt74KExWRqZmBTf7P3c=,iv:HZub5qgwJzgmJeztfY+Hg5SVkAdvNzNeP4y2WUc9Ogo=,tag:pUJ2C414qCqdsBt7SoqfQA==,type:str]
    pgp:
        - created_at: "2021-11-12T19:39:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1GgX0oycVV1ARAAvyOt/xxlj+Hm5tlcya3MT7/HL0BQqJNOHbzHFo6h5m6T
            5wjAbJOk+2w1M2OnwBRyil5oSXaSu44IeqTnSK2Cb04vvHjGE8vKcpG9vXJ5CD+H
            yiQta1jk3ItKBdSsUVsQAymbTPeCDa411/V0jqTgLErisFErnYGCHVv3hyzfeiA9
            iraJ7z+DZkUHhHFB0sqcxfY5BBUunllzwwjG2Jaux+bFCwT+A/U/qizO3KS3nm2q
            Qceh+LKuwYKFlOuZMC+Hv2Ln1NQHBr5TIGowt+4NRbdX6+1zrtKxyPeb6ExAeBAo
            bWgJe3qjXv3u5Gwe/JAQLnhCYNseJv8uOzlR2EgC9NbjOeRfnbyXXc+P5VDRdpeg
            jP2sH7e1fqi+STiTkXB2QQgQyEzfA1Ae072HtvvKIqCoVSXs6PJbbv0mtzQo3W+h
            nLNgVtD/vOcYIetVk9SKq6iJ5p6tz9Ukezghe69JVz7D2bXOB0Tc8rJymQ3Jvycr
            EX1ZhpSTmVjiviMFpCfgEf3ncj7dxaRz0CUv3PKhaiUJoNWYhxyjxZBD5PA1PJOm
            pW9uYM8FG0jXpoV98yis7wLXMXpNMxPCv/KGsTMRKWhhVgeuJ7BoJmLKYb90uyZA
            cU+LuMCHBrfXtjyq+2qTsNJR8MWXP9bvP1vpT8qt+V2Pj1YClMG3Z+y5fD9D0x/S
            XAHH2+u7uBRxLGGhMrXVxtTkmMjFQg7f2vbLWIw/leJM/fnwqBH0R4PqbU+Xdjl7
            1/x6SddhNTbY8uznenRAu1p82NBsLB/JginyLT0o8tA2AfzJwktFTllcFzwr
            =sq5v
            -----END PGP MESSAGE-----
          fp: 17299B027FB6B1C68971411B5FF3C7583ADD1EFB
        - created_at: "2021-11-12T19:39:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XaZDWXjonIARAAkovgkZaQOCzBtO2gmR5MeVgAnj3OpcpLv54PgFyLl7jw
            /5fzKTLpo5fjgdQEobxoON7pXDRED8XWZkhNLscw+43ke9QSLrqL3mKXzD+bXM1i
            5mamwzgz3UUsGlOvkwjW8kCOFKPDT8JQv6aQuabEBmW7s6EWs8rAJAFm57ZXYCiI
            1G7XBzHvhcQDMGvVVsFwv/3tqzgMzr4/AnlH27jOSpMS+XunqrhHizsuzx8DH4Dp
            R6qqCDzfs7RP14resMI+1fL60qgjw0ME+EwOXuQRbI7Re5bm+4O4dclHsgWRnaiT
            QJKaJ43x76trT1R6YLM08+ITx+JK07ksvD1T1zuUdfsX+P6jPRqLO0AQs+47poyF
            xSIWYrVsKC+lZkmy9US55HDU/C0I3VnxsPKrYixqU8Ow4Eokd6bfD9yNT1+s8HVU
            xGhTmyuhh+KtzMwMuHzI6hC3exZ9VIC3Q7A5tFv7A7wVEq68cmZ6ou3vYdUuQPJb
            qKovvKti3xE5PQPpgnDQm44MRqR/4nZmQWbyUetYJk86yG3jIlI6FfTXYinJm9Pk
            Fyr3xnkSbRuX6SGBROKwvf9WtFGaawmZU3uyXWo07FeCnKytfZxBY147xdB449to
            vrDo4wtVx0uocKR6dZzMK8k8pRSHP8iKT+u7fucTVgDoQJMjZA1CAc8+Tw+UdobS
            XAF7uEzXjhPSPDyThNK8SeR1fEjI5L7on8diurspT/JWiuqAWHJJn7E1lqCpN2/G
            mSnnxd1gnMtiOw8AFPL4mEcx2w7yLmF3qbZqQt8Qh2U/owuKRQ5lw6TNuu71
            =nCGM
            -----END PGP MESSAGE-----
          fp: 147C67A0D68CF30B3C7ED3AB43A189D025B879AC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
