# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:v0gbiguhBcKBXQ==,iv:+L/CuD9Gya94tCQXFqTzqbWZ2oGVNL88Rv3VcaE9YxI=,tag:P/z3/XGqP+m9vcaOLUtjIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-10T20:14:37Z"
    mac: ENC[AES256_GCM,data:CNvPJ8qCelKtXN62gxCYZ7aG7KvPy8dFLxSlMTx9epF/LudOhZHaFhw3XsohVBI8IrG7kjkb2l4iMmvvxM3pvrch7qdyVN/1SDQAdhiVuqNKI0RJFqWv2WGsQr28egh8rKKWnePfSLKyHLHFvCwIpW0SsaG8eR+fsttldEYqO1k=,iv:QQULeGHXHB+0sMI3cjz3FBtclPCBq7y/UKBgNKg+IKw=,tag:r11AfAGpB20jaFZxoUHt4g==,type:str]
    pgp:
        - created_at: "2021-08-10T20:14:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1GgX0oycVV1ARAAw3scBXfmcdjE2w4eMJeg91ieVK2gd5Clvyl39PmyrQia
            CRqP2K1JAGOrFKCs2lL1hc4rwFbYCYNqBIOOt6B/o4hUeAA7E6XvsDnaUGgWJ6+u
            dLeoYv2VbQ/vXOehyi7WQ/BKZE2kJxpjXICCjmEkENoDIVUyuUgkH2jn3NYD22Iv
            Vox2z/PpulqXnyKz+K7ew5jpC25HitKs0ROIPrkb2WL2khe9cLJcmWGRfFyvL0Kr
            VhuP3WRZ8ubNp5X/88PyHLjE9mZYMReI3I42AA/wApemnQmvbLFn3Y5TD4F9SUjg
            dFWKDjxBJI937hvGm3isPPCz9iSL+rn/fBvfM7P9UGO9EPbBmhlSE473jHCLc54z
            EVEC2Voz84OiGiw/ODFn3nOpw9eV+zT3EP7go3sS2pN5su1+ym6pJywbuCdJfluB
            pDSbzH2JWgl6NQYlTIwCCYidJwgMrg8ErW6sORE9vqj5Np8p4TlTvqkktPu45ccu
            shOvVt1f9wvLx2rbDqhuh6BfB+P6nFVep591qQSYOxGOwVLSrruiMJRGNPmyFZLG
            KOoA8+6gRyP/L3cks2LdClHSxQrxVGI276xyNALOscu0SeZtVS44UY2wgHpZBCyk
            3pL+BkqFhLToszpb6lSpunT2Xki4xoJC2uz7gwq3sUCXmjx34XNSSsYYdJeEm7XS
            XgFIjubLm0lydXuhoYDcY0jZnWARVmjREtfotVyeKJymU/5zwvtkGs4IQUPZ+1go
            hSqHmhX9NJ3w0xCvI73LFm01Yb8LW2h1WZebcjpJ6T7Z/yF7Jv+OSfgAfp3F56Q=
            =IbBg
            -----END PGP MESSAGE-----
          fp: 17299B027FB6B1C68971411B5FF3C7583ADD1EFB
        - created_at: "2021-08-10T20:14:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XaZDWXjonIAQ//eKLjU9wA8sVfuDqOS2K/6yKT5tzmr9LFySz7Rb3SWOTb
            CsG7WBLc2p6unuenyRQcg3UDuQtRO4G4Ib66cgN7ukao8EvR+H4Geyn8UOPCQCfY
            b/+rvXhzlRxV0UZWAW6xDjQJfhjprP+UQHkvI6YS5HPRYReGn3ZGl03e6X/gohg3
            dh8pyH7rRYKgPLcqplBIuoV3wjd5yll914TC86CwrwTe7+OK0i8IdlQO2bkUYbKN
            36p8rkSYrXnQphXQZAj+Rqngzxg+ydcSvRDRD5h2/RD3Ydxfgz87hrvAXe7IyoBE
            x36kFPNif9miG9rwfMbngkJ+BtVdsgV1Lc1apicfJfhqL2WDiXDfxLIXeczv9pYf
            4HNbNBySFwH2xTwZ3r+PjNaIDc0A2IENbf3z2S2ELG+Me0pZ17HSajUmfeI3rP41
            sHYL3MgMa0/37LREgN4GgVUPSLIzcW9yiIA60/QYS0z1uhqKCANLUSaV71ISoN4E
            fwfjbnOpC75rKVpqVmOeUpByjstCDyAwW1QnDcsGlK8lwY8oxIfst541NIq/HU7T
            ufR0oH9yq19K5A4L5x6w0cG0NCxHEeXfgcDjdSv4I7h+D0CPkk0m6o6BpCQ5JDuY
            yyEp50RyUrwShkIcd9+sfdgS7uRexs9fzqVjpXEsqPOApA0RwZwfb67+HAVg2ozS
            XgFsrGNB2FlNSLXK2TVqCQKCam/Fjlp/rXp4GxhRNfHPKwKHCXaTIH47U0D9vacr
            MiHwTDceGts+sRTfsyqZAmyq+UaPFNpNYcyDhXL2Pv6hkcejL0VCa/eh/fD3bM4=
            =2S3K
            -----END PGP MESSAGE-----
          fp: 147C67A0D68CF30B3C7ED3AB43A189D025B879AC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
